Friendlier parser error output
Keep additional lex/parse state so we can give error locations.
Example:

error: expected step or partial
error: at line 14 column 0 near step b
error: in file /var/home/joe/src/df/bknit/tests/tmp/plan.knit